services:
  dnsmasq:
    image: andyshinn/dnsmasq
    cap_add:
      - NET_ADMIN
    command: --log-facility=-
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    network_mode: 'host'
  celery-worker:
    build:
      context: ../backend
      dockerfile: ../backend/Dockerfile
    command: >
      bash -c "source /venv/bin/activate &&
               uv pip install watchdog &&
               uv pip install -r requirements.txt &&
               watchmedo auto-restart --directory=/code --pattern=*.py --ignore-patterns="/code/zane_api/tests/**" --recursive -- celery -A backend worker -E -l info"
    volumes:
      - ../backend:/code
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - db
      - redis
    network_mode: 'host'
  celery-beat:
    build:
      context: ../backend
      dockerfile: ../backend/Dockerfile

    command: >
      bash -c "source /venv/bin/activate &&
               uv pip install watchdog &&
               uv pip install -r requirements.txt &&
               watchmedo auto-restart --directory=/code --pattern=*.py --ignore-patterns="/code/zane_api/tests/**" --recursive -- celery -A backend beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - ../backend:/code
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      REDIS_URL: redis://redis:6379/0
      DB_HOST: db
      DB_PORT: 5432
      CADDY_PROXY_ADMIN_HOST: http://host.docker.internal:2019
    depends_on:
      - db
      - redis
  registry:
    image: registry:2
    container_name: zane-registry
    restart: always
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./registry/auth:/auth
      - ./registry/data:/data
      - registry-lib-data:/var/lib/registry
    ports:
      - "9989:5000"
  redis:
    image: valkey/valkey:7.2.5-alpine
    container_name: zane-redis
    volumes:
      - redis-data:/data
    ports:
      - "6381:6379"
  db:
    image: postgres:16-alpine
    container_name: zane-db
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zane
    ports:
      - "5434:5432"
  adminer:
    image: adminer
    container_name: zane-adminer
    restart: always
    ports:
      - "8081:8080"
  redis-gui:
    image: redis/redisinsight
    container_name: zane-redis-gui
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8089:5540"
    volumes:
      - redisinsight:/data
volumes:
  pg-data:
  redis-data:
  redisinsight:
  caddy-data:
  registry-lib-data:
  pgadmin-data:
