name: Biome Check Formatting
on:
  pull_request:

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Setup Biome
        uses: biomejs/setup-biome@b9af8bac86b0da736cfbfadbfeb3f7463da083f2 # v2.1.1
        with:
          version: 1.5.3
      - name: Run Biome
        run: biome check .
