name: Django Tests

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: zane
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5434:5432
    
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Set up Python 3.11.7
        uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2.3.4
        with:
          python-version: 3.11.7

      - name: Install dependencies
        run: |
          cd backend
          pip install uv==0.1.0
          uv venv
          uv pip install -r requirements.txt

      - name: Run tests
        run: |
          cd backend
          source .venv/bin/activate
          python manage.py test --parallel
